package io.jenkins.plugins.checks.api;

import org.junit.jupiter.api.Test;

import java.util.Optional;

import static io.jenkins.plugins.checks.api.ChecksImageAssert.assertThat;

class ChecksImageTest {
    @Test
    void shouldConstructCorrectly() {
        final ChecksImage image = new ChecksImage("warnings-chart",
                "https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/job/master/",
                "charts generated by warning-ng-plugin");

        assertThat(image)
                .hasAlt(Optional.of("warnings-chart"))
                .hasImageURL(Optional.of("https://ci.jenkins.io/job/Plugins/job/warnings-ng-plugin/job/master/"))
                .hasCaption(Optional.of("charts generated by warning-ng-plugin"));
    }
}
