@startuml

skinparam componentStyle uml2
skinparam component {
  BorderColor #a0a0a0
  BackgroundColor #f8f8f8
}

[API] <<..checks.api>>
[Test] <<..checks.api.test>>
[Steps] <<..checks.steps>>
[Status] <<..checks.status>>
[Checks] <<..checks>>

[Steps] --> [API]
[Status] --> [API]
[Checks] --> [API]
[Test] --> [API]

@enduml
