@startuml

skinparam componentStyle uml2
skinparam component {
  BorderColor #a0a0a0
  BackgroundColor #f8f8f8
}

[API] <<..checks.api>>
[Steps] <<..checks.steps>>
[Status] <<..checks.status>>
[Utils] <<..checks.utils>>
[Checks] <<..checks>>

[Steps] --> [API]
[Steps] --> [Utils]
[Status] --> [API]
[Status] --> [Utils]
[Checks] --> [API]

@enduml
